### PR TITLE
Finish to bevy 0.4 on nightly branch

### PR DESCRIPTION
**Pull request by ryanleecode**

### CODE REVIEW

**Comment by frondeus** [comment]
Isn't it done by #52?

**Comment by ryanleecode** [comment]
Yah Im just adding to his branch. There were a few changes

**Comment by joshuajbouw** [comment]
Thanks for this, been busy this year for xmas. Will check shortly and clean up where needed.

**Review by joshuajbouw — APPROVED** [review]
Looks good. I'll pull it in and add in anything that may be missing following.

**Pull request merged**
