### PR TITLE
Floor the UV in the shader so that tile bondaries don't sparkle when …

### PR DESCRIPTION
**Pull request by alec-deason**
…the camera moves by fractional pixels

### CODE REVIEW

**Comment by alec-deason** [comment]
The CI failure looks to be hexasphere publishing breaking changes again. It's not related to this PR.

**Comment by joshuajbouw** [comment]
CI is fixed with a patch I made. Do rebase and fix conflicts please. If this only exists on `bevy_nightly`, then keep it here else choose `master` branch. Thanks buddy.

**Comment by joshuajbouw** [comment]
Going to close this, can you please merge this into Master instead?

**Comment by alec-deason** [comment]
Done: #57

**Pull request closed without merging**
